name: cameraai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - opencv-python=4.10.0.82
  - pip
  - pillow
  - pip:
      - ultralytics
      - streamlit
      - mediapipe
